language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 2.1.302
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      dotnet: 2.1.302

script:
  # Does the repo compile
  - dotnet build
